version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/app
      - ./:/go/src/app
    ports:
      - 8080:8080
    env_file:
      - env/dev.env
